import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { chromium } from 'playwright';
import { normalizeConfig } from '../src/physics.js';
import { runExperiment, MODEL_VERSION } from '../src/experiments.js';
import { getConsumerGuide, describeGuideResults } from '../src/consumer-guide.js';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const version=JSON.parse(await fs.readFile(path.join(root,'package.json'),'utf8')).version;
const output=path.join(root,'output','playwright',`consumer-guide-v${version}`);
const baseURL=process.env.SUSPENSION_TEST_URL||'http://127.0.0.1:5173';
await fs.mkdir(output,{recursive:true});
const browser=await chromium.launch({headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});
const page=await context.newPage(),checks=[],errors=[];
page.on('pageerror',error=>errors.push(error.message));
const records=()=>page.evaluate(()=>window.suspensionLab.getExperiments());
const config=()=>page.evaluate(()=>window.suspensionLab.getConfig());
async function ready(){await page.waitForFunction(()=>window.suspensionLab?.productReady);await page.evaluate(()=>window.suspensionLab.productReady);await page.evaluate(()=>window.suspensionLab.setRunning(false));}
async function idle(){await page.waitForFunction(()=>!window.suspensionLab.getProductState().busy,{}, {timeout:45000});}
async function openProject(project){await page.locator('#project-import-file').setInputFiles({name:'guide-test.suspension.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(project))});await idle();}
const project=(config,runs)=>({type:'suspension-lab-project',schemaVersion:1,modelVersion:MODEL_VERSION,name:'사용자 작업 보존 시험',exportedAt:new Date().toISOString(),config,runs});
try{
  await page.goto(baseURL);await ready();
  assert.equal(await page.locator('#consumer-guide').isVisible(),true);
  assert.equal(await page.locator('#run-consumer-guide-btn').isEnabled(),true);
  const firstGuide=await page.locator('#consumer-guide').boundingBox(),firstViewport=await page.locator('#viewport').boundingBox(),firstTelemetry=await page.locator('.telemetry-section').boundingBox();
  assert.ok(firstGuide.height<=90,'wide first guide remains compact without shrinking its text');
  assert.ok(firstViewport.height>=420,'wide original 3D viewport retains 420px at 1000px height');
  assert.ok(firstTelemetry.y+firstTelemetry.height<=1000,'first bench scene and live instruments fit the desktop');
  await page.screenshot({path:path.join(output,'first-experience.png'),fullPage:true});
  const current=normalizeConfig({structure:'multilink',holderMode:'fixed',springType:'air',road:'step',speed:67,reboundDamping:5300});
  const old=runExperiment({road:'pothole'},{duration:1,name:'사용자가 남긴 기록'});
  await openProject(project(current,[old]));
  const before=await config();assert.deepEqual(before,current);
  await page.locator('#run-consumer-guide-btn').click();
  await page.locator('#cancel-consumer-guide-btn').click();await idle();
  assert.deepEqual(await records(),[old]);assert.deepEqual(await config(),before);
  assert.match(await page.locator('#consumer-guide-status').innerText(),/중단/);
  checks.push('first-screen A/B entry and actual cancellation preserve working settings and existing records');
  await page.locator('#run-consumer-guide-btn').click();await idle();
  const all=await records(),guide=getConsumerGuide();
  assert.equal(all.length,3);assert.deepEqual(all.find(run=>run.id===old.id),old);
  assert.deepEqual(await config(),before);
  const selected=await page.evaluate(()=>window.suspensionLab.getProductState().selected);
  assert.equal(selected.length,2);
  const pair=selected.map(id=>all.find(run=>run.id===id));
  assert.equal(pair[0].config.reboundDamping,900);assert.equal(pair[1].config.reboundDamping,4200);
  assert.deepEqual(Object.entries(pair[0].config).filter(([key])=>key!==guide.parameter),Object.entries(pair[1].config).filter(([key])=>key!==guide.parameter));
  assert.equal(await page.evaluate(()=>window.suspensionLab.getWorkspaceView()),'experiments');
  assert.equal(await page.locator('#experiment-overlay-mode').inputValue(),'acceleration');
  assert.equal(await page.locator('#experiment-overlay-chart [data-experiment-id]').count(),2);
  const interpretation=describeGuideResults(pair),copy=await page.locator('#consumer-guide-results').innerText();
  for(const sentence of interpretation.sentences)assert.ok(copy.includes(sentence));
  assert.match(copy,/최적 설정이나 안전 판정이 아닙니다/);
  assert.equal(await page.locator('#consumer-guide-results').evaluate(node=>!!node.closest('#experiment-workspace')),true);
  await page.screenshot({path:path.join(output,'completed-ab.png'),fullPage:true});
  checks.push('complete guide changes one coefficient, selects two saved curves and displays the actual bounce/acceleration/contact tradeoff');
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),true);
  assert.equal(await page.locator('#consumer-guide-results').isVisible(),true);
  assert.equal(await page.locator('[data-guide-action="compare"]').isEnabled(),true);
  assert.equal(await page.locator('[data-guide-action="save"]').isEnabled(),true);
  await page.locator('[data-guide-action="compare"]').click();
  assert.equal(await page.locator('#experiment-overlay-chart [data-experiment-id]').count(),2);
  await page.screenshot({path:path.join(output,'completed-ab-narrow.png'),fullPage:true});
  await page.evaluate(()=>window.suspensionLab.setWorkspaceView('bench'));
  assert.equal(await page.locator('#consumer-guide-results').isVisible(),false);
  assert.equal(await page.locator('#view-consumer-guide-btn').isEnabled(),true);
  await page.locator('#view-consumer-guide-btn').click();
  assert.equal(await page.evaluate(()=>window.suspensionLab.getWorkspaceView()),'experiments');
  assert.equal(await page.locator('#consumer-guide-results').isVisible(),true);
  await page.setViewportSize({width:1440,height:1000});
  await page.evaluate(()=>window.suspensionLab.setWorkspaceView('analysis'));
  assert.equal(await page.locator('#consumer-guide').isVisible(),false);
  assert.equal(await page.locator('#consumer-guide-results').isVisible(),false);
  await page.evaluate(()=>window.suspensionLab.setWorkspaceView('bench'));
  const returnedTelemetry=await page.locator('.telemetry-section').boundingBox();
  assert.ok(returnedTelemetry.y+returnedTelemetry.height<=1000,'saved guide results do not push live instruments below the desktop');
  await page.locator('#view-consumer-guide-btn').click();
  checks.push('completed 390px guide stays readable with working compare/save controls; results stay scoped away from live bench and analysis');
  const reportEvent=page.waitForEvent('download');await page.locator('#experiment-report-btn').click();
  const report=await reportEvent,reportPath=path.join(output,'first-ab-report.html');await report.saveAs(reportPath);
  const reportText=await fs.readFile(reportPath,'utf8');assert.match(reportText,/A\/B 예시에서 관찰한 차이/);assert.match(reportText,/안전 판정이 아닙니다/);
  const projectEvent=page.waitForEvent('download');await page.locator('[data-guide-action="save"]').click();
  const saved=await projectEvent,savedPath=path.join(output,'first-ab.suspension.json');await saved.saveAs(savedPath);
  const exported=JSON.parse(await fs.readFile(savedPath,'utf8'));assert.deepEqual(exported.config,before);assert.deepEqual(exported.runs,all);
  await page.reload();await ready();assert.deepEqual(await config(),before);assert.deepEqual(await records(),all);
  assert.equal(await page.locator('#consumer-guide-results').isVisible(),true);
  await openProject(exported);assert.deepEqual(await records(),all);assert.deepEqual(await config(),before);
  checks.push('plain-result report and complete project export/import/relaunch keep input conditions and example records');
  const full=Array.from({length:11},()=>runExperiment({},{duration:1}));await openProject(project(before,full));
  assert.equal(await page.locator('#run-consumer-guide-btn').isDisabled(),true);
  assert.match(await page.locator('#consumer-guide-status').innerText(),/두 개를 보관할 공간/);
  assert.deepEqual(await records(),full);
  checks.push('capacity blocks the guide before calculation with an actionable message and no discarded work');
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),true);
  await page.screenshot({path:path.join(output,'guide-narrow.png'),fullPage:true});
  assert.deepEqual(errors,[]);
  await fs.writeFile(path.join(output,'report.json'),JSON.stringify({passed:true,checks,pageErrors:errors,realAppDataTouched:false},null,2));
  console.log(JSON.stringify({passed:true,checks:checks.length,output}));
}finally{await context.close();await browser.close();}
